### ISSUE TITLE
Can we  add line_spacing?

### ISSUE THREAD

**Issue by egenc** [microsoft/genalog#44]
Hello, I am trying to add linespacing. Even though I add new lines manually from txt, it still removes them. 

```
with open(txt_path, 'r') as f:
    text = f.read()

# Initialize Content Object
text = text.replace('\n', '\n\n')
paragraphs = text.split('\n\n\n')
```

printing paragraph gives the demanded result, however,  `default_generator.set_styles_to_generate(new_style_combinations)` somehow removes blank lines.  Thank you in advance

**Comment by laserprec** [comment]
Hey there, thanks for the feedback! Could you please provide a little more of context here? Did you run into an issue following the documentation? If I am interpreting correctly, are you trying to increase the margin between paragraphs?

**Comment by laserprec** [comment]
Closing this issue due to a lack of participation/clarification.
