### ISSUE TITLE
Retrieve position of rendered document

### ISSUE THREAD

**Issue by parsa-ra** [microsoft/genalog#50]
I want to use this tool to generate a synthetic dataset for the detection phase of the OCR pipelines, I wonder if there is a way to get a location (bounding box) of each word that is rendered to the final documents?

**Comment by mayug** [comment]
Did you find a way to do this? One idea is to use render_pdf() and then use something like pdfminer on the pdf to get the bounding boxes of layout regions or characters.

**Comment by parsa-ra** [comment]
We had to write a complete program based on Cairo and Pango to just do that, at first we employed the pdfminer, but we saw that it fails in most cases as bounding boxes were not accurate in complex templates.
